# Generated by Django 4.0 on 2021-12-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
