# Generated by Django 4.0 on 2021-12-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageNews', '0003_image_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_news',
            old_name='question_id',
            new_name='news_id',
        ),
    ]
