# Generated by Django 4.0 on 2021-12-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageQuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dateCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
