# Generated by Django 4.0 on 2021-12-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageQuit', '0002_alter_question_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
    ]
