# Generated by Django 4.0 on 2021-12-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ManageQuit', '0003_remove_question_datecreated_remove_question_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
