# Generated by Django 4.0 on 2021-12-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageQuit', '0004_question_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
    ]
