# Generated by Django 4.0 on 2021-12-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageQuit', '0008_image_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Question',
        ),
    ]
