# Generated by Django 4.0 on 2021-12-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=355)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('countryCode', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=355)),
                ('countryCode', models.CharField(max_length=55)),
                ('newConfirmed', models.IntegerField()),
                ('totalConfirmed', models.IntegerField()),
                ('newDeaths', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=355)),
                ('countryCode', models.CharField(max_length=55)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
