# Generated by Django 4.0 on 2021-12-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='countryCode',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
