# Generated by Django 4.0 on 2021-12-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Covid19', '0003_alter_global_date_alter_summary_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
