# Generated by Django 4.0 on 2021-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid19', '0004_delete_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=355)),
                ('countryCode', models.CharField(max_length=55)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
